# Generated by Django 5.0 on 2023-12-18 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='team',
        ),
    ]
