# Generated by Django 5.0 on 2023-12-24 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula1', '0002_remove_race_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_races',
            new_name='races',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_wins',
            new_name='wins',
        ),
    ]
