# Generated by Django 5.0 on 2023-12-24 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula1', '0003_rename_team_name_team_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='track_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='track_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='track_name',
            new_name='name',
        ),
    ]
